import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api.js';
import { useAuth } from '../lib/auth.jsx';
import { fmtDate, fmtDateTime, materialLabel, titleCase } from '../lib/format.js';

const MATERIALS = ['plastic', 'paper', 'glass', 'metal', 'e_waste', 'organic', 'other'];

export default function Collections() {
  const { user } = useAuth();
  const [rows, setRows] = useState([]);
  const [filters, setFilters] = useState({ from: '', to: '', material: '' });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.collections(filters);
      setRows(res.data);
      setError('');
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [filters]);

  useEffect(() => {
    load();
  }, [load]);

  const totalKg = rows.reduce((s, r) => s + Number(r.weight_kg), 0);

  const filterSummary = () => {
    const parts = [];
    if (filters.from) parts.push(`From ${fmtDate(filters.from)}`);
    if (filters.to) parts.push(`To ${fmtDate(filters.to)}`);
    if (filters.material) parts.push(`Material: ${materialLabel(filters.material)}`);
    return parts.length ? parts.join('   ·   ') : 'None — all records';
  };

  const downloadPdf = async () => {
    // Loaded on demand so the ~700 KB PDF engine never delays first paint.
    const { buildReportPdf } = await import('../lib/pdf.js');
    buildReportPdf({
      title: 'Collection Activity Log',
      subtitle: 'Every collection recorded by the community',
      orientation: 'landscape',
      columns: [
        { key: 'collected_on', label: 'Date', width: 28, value: (r) => fmtDate(r.collected_on) },
        { key: 'picker_id', label: 'Picker ID', mono: true, width: 36, value: (r) => r.picker?.picker_id || '—' },
        { key: 'name', label: 'Name', bold: true, value: (r) => r.picker?.full_name || '—' },
        { key: 'region', label: 'County', width: 30, value: (r) => r.picker?.region?.name || '—' },
        { key: 'material', label: 'Material', width: 28, value: (r) => materialLabel(r.material) },
        { key: 'weight_kg', label: 'Weight (kg)', align: 'right', width: 28, value: (r) => Number(r.weight_kg).toFixed(1) },
      ],
      rows,
      summary: [
        { value: rows.length, label: 'Records' },
        { value: totalKg.toFixed(1), label: 'Total kilograms' },
        { value: rows.length ? (totalKg / rows.length).toFixed(1) : '0.0', label: 'Average per record' },
        { value: new Set(rows.map((r) => r.picker?.picker_id).filter(Boolean)).size, label: 'Waste pickers' },
      ],
      meta: {
        'Generated on': fmtDateTime(),
        'Generated by': `${user?.full_name || 'Administrator'} (${titleCase(user?.role)})`,
        Filters: filterSummary(),
        Records: `${rows.length} row${rows.length === 1 ? '' : 's'}`,
      },
      filename: `collection-activity-${new Date().toISOString().slice(0, 10)}.pdf`,
    });
  };

  return (
    <>
      {error && <div className="alert error">{error}</div>}

      <div className="stat-grid">
        <div className="stat green">
          <div className="label">Records shown</div>
          <div className="value">{rows.length}</div>
        </div>
        <div className="stat blue">
          <div className="label">Total weight</div>
          <div className="value">{totalKg.toFixed(1)}</div>
          <div className="sub">kilograms</div>
        </div>
        <div className="stat amber">
          <div className="label">Average per record</div>
          <div className="value">{rows.length ? (totalKg / rows.length).toFixed(1) : '0.0'}</div>
          <div className="sub">kilograms</div>
        </div>
      </div>

      <div className="card">
        <div className="card-head">
          <div className="filters">
            <div className="field">
              <label>From</label>
              <input
                type="date"
                value={filters.from}
                onChange={(e) => setFilters({ ...filters, from: e.target.value })}
              />
            </div>
            <div className="field">
              <label>To</label>
              <input
                type="date"
                value={filters.to}
                onChange={(e) => setFilters({ ...filters, to: e.target.value })}
              />
            </div>
            <div className="field">
              <label>Material</label>
              <select
                value={filters.material}
                onChange={(e) => setFilters({ ...filters, material: e.target.value })}
              >
                <option value="">All materials</option>
                {MATERIALS.map((m) => (
                  <option key={m} value={m}>
                    {m.replace('_', '-')}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <button className="btn" disabled={!rows.length} onClick={downloadPdf}>
            Download PDF
          </button>
        </div>

        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Picker ID</th>
                <th>Name</th>
                <th>Region</th>
                <th>Material</th>
                <th>Weight</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={6} className="empty">
                    Loading...
                  </td>
                </tr>
              ) : rows.length === 0 ? (
                <tr>
                  <td colSpan={6} className="empty">
                    No collection activity for this period.
                  </td>
                </tr>
              ) : (
                rows.map((r) => (
                  <tr key={r.id}>
                    <td>{r.collected_on}</td>
                    <td className="mono">{r.picker?.picker_id || '—'}</td>
                    <td>{r.picker?.full_name || '—'}</td>
                    <td>{r.picker?.region?.name || '—'}</td>
                    <td style={{ textTransform: 'capitalize' }}>{r.material.replace('_', '-')}</td>
                    <td>{Number(r.weight_kg).toFixed(1)} kg</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
